import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SharedNavbar from 'http://localhost:3000/share-components/navbar.js';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <SharedNavbar title="Pop Punk" />
      <main className={styles.main}>

        <div className={styles.center}>
          <h1>Two step <br/> the heartache <br/>away!</h1>
        </div>

      </main>
    </>
  )
}
